### ISSUE TITLE
Broken <link> tag. Favicon no longer appears.

### ISSUE THREAD

**Issue by beardedlinuxgeek** [Leimi/nautsbuilder#30]
I've check on multiple browsers, even on my phone, and the favicon link is always rendered as:

```html
<li<nk rel="icon" type="image/png" href="img/favicon.png">
```

I spent a couple minutes digging through the source code here, but the cause wasn't obvious. Maybe something with the build process?

**Comment by Leimi** [comment]
Hey,

Thanks for letting me now. It should be fixed now!

Since I publish new code quick&dirty style (SFTP upload by hand), I must have put a typo in the code at the wrong time without noticing... duh.
