### ISSUE TITLE
Local build of nautsbuilder not working

### ISSUE THREAD

**Issue by D4RKONION** [Leimi/nautsbuilder#31]
I was hoping to contribute to this project. I cloned the git and started up the php server, but I'm getting an old set of data, specifically, around the time that penny fox was in beta.

I'm getting bad request errors in the console, and I think that possibly the current version on git is still trying to grab data from on old google sheets URL, from before they moved everything over to drive.

Obviously there's a working version for the main site because that's up to date. Could you shine some light on this? Am I doing something wrong or is the git not up to date?

**Comment by r0estir0bbe** [comment]
Oh yeah, sorry. I forgot to mirror the upload to the webserver. You need to update the [tabletop library](https://github.com/jsoma/tabletop).

**Comment by r0estir0bbe** [comment]
82fe48358d0bfd91224bae01a54e90315bdae45c should fix the bad request errors.
f23b43820487962a7487f44fa623c9a09843486c updated the data inside the repository, while 4ed588208dd797c7fd2ff6601644a7ff3b23c1c9 fixed that Nautsbuilder run locally always used the outdated dev data.
Please tell me if these commits fixed the problem for you.

**Comment by D4RKONION** [comment]
This has solved the problem. I look forward to contributing in the future!
